------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:13:46 #1 explorer] 
[ObjectDB 2.6.9_09] javax.persistence.PersistenceException
Attempt to open a database file 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.G(LFL.java:939)
	at com.objectdb.o.LFL.B(LFL.java:885)
	at com.objectdb.o.LFL.B(LFL.java:794)
	at com.objectdb.o.SFL.<init>(SFL.java:235)
	at com.objectdb.o.MST.<init>(MST.java:123)
	at com.objectdb.o.MST.aN(MST.java:105)
	at com.objectdb.o.MSF.Vn(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:782)
	at com.objectdb.jpa.EMF.an(EMF.java:131)
	at com.objectdb.o.OMF.am(OMF.java:693)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:150)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:15:40 #1 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' has been recovered (tr. 35-35)

[2017-02-23 11:15:40 #2 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is opened by 256@ASIER

[2017-02-23 11:23:26 #3 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is closed by 256@ASIER

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:27:23 #1 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' has been recovered (tr. 36-36)

[2017-02-23 11:27:23 #2 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is opened by 6376@ASIER

[2017-02-23 11:29:34 #3 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is closed by 6376@ASIER

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:36:21 #1 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is opened by 11804@ASIER

[2017-02-23 11:37:02 #2 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is closed by 11804@ASIER

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:38:25 #1 explorer] 
[ObjectDB 2.6.9_09] javax.persistence.PersistenceException
Attempt to open a database file 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.G(LFL.java:939)
	at com.objectdb.o.LFL.B(LFL.java:885)
	at com.objectdb.o.LFL.B(LFL.java:794)
	at com.objectdb.o.SFL.<init>(SFL.java:235)
	at com.objectdb.o.MST.<init>(MST.java:123)
	at com.objectdb.o.MST.aN(MST.java:105)
	at com.objectdb.o.MSF.Vn(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:782)
	at com.objectdb.jpa.EMF.an(EMF.java:131)
	at com.objectdb.o.OMF.am(OMF.java:693)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:150)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:38:29 #1 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' has been recovered (tr. 37-37)

[2017-02-23 11:38:29 #2 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is opened by 7380@ASIER

[2017-02-23 11:39:57 #3 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is closed by 7380@ASIER

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:40:48 #1 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' has been recovered (tr. 38-38)

[2017-02-23 11:40:48 #2 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is opened by 11224@ASIER

[2017-02-23 11:41:07 #3 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is closed by 11224@ASIER

------------------------------------------------------------------------------------------------------------------------

[2017-02-23 11:42:09 #1 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' has been recovered (tr. 39-39)

[2017-02-23 11:42:09 #2 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is opened by 1544@ASIER

[2017-02-23 11:43:30 #3 store] 
Database 'G:\Informatika\4 curso\Ingenieria del software\RuralHouses\resources\ruralHouses.odb' is closed by 1544@ASIER

